# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\document\大四上学习\计算机网络\project2\rtp-new\Client\ClientUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1074, 578)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("source/icon/titleIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/*\n"
"* The MIT License (MIT)\n"
"*\n"
"* Copyright : http://blog.csdn.net/liang19890820\n"
"*\n"
"* Author : 一去丶二三里\n"
"*\n"
"* Date : 2016/07/22\n"
"*\n"
"* Description : 黑色炫酷\n"
"*\n"
"*/\n"
"\n"
"/**********子界面背景**********/\n"
"QWidget#customWidget {\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"\n"
"/**********子界面中央背景**********/\n"
"QWidget#centerWidget {\n"
"        background: rgb(50, 50, 50);\n"
"}\n"
"\n"
"/**********主界面样式**********/\n"
"QWidget#mainWindow {\n"
"        border: 1px solid rgb(50, 50, 50);\n"
"        background: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QWidget#messageWidget {\n"
"        background: rgba(68, 69, 73, 50%);\n"
"}\n"
"\n"
"QWidget#loadingWidget {\n"
"        border: none;\n"
"        border-radius: 5px;\n"
"        background: rgb(50, 50, 50);\n"
"}\n"
"\n"
"QWidget#remoteWidget {\n"
"        border-top-right-radius: 10px;\n"
"        border-bottom-right-radius: 10px;\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        background: rgb(50, 50, 50);\n"
"}\n"
"\n"
"StyledWidget {\n"
"        qproperty-normalColor: white;\n"
"        qproperty-disableColor: gray;\n"
"        qproperty-highlightColor: rgb(0, 160, 230);\n"
"        qproperty-errorColor: red;\n"
"}\n"
"\n"
"QProgressIndicator {\n"
"        qproperty-color: rgb(175, 175, 175);\n"
"}\n"
"\n"
"/**********提示**********/\n"
"QToolTip{\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        background: white;\n"
"        color: black;\n"
"}\n"
"\n"
"/**********菜单栏**********/\n"
"QMenuBar {\n"
"        background: rgb(57, 58, 60);\n"
"        border: none;\n"
"}\n"
"QMenuBar::item {\n"
"        padding: 5px 10px 5px 10px;\n"
"        background: transparent;\n"
"}\n"
"QMenuBar::item:enabled {\n"
"        color: rgb(227, 234, 242);\n"
"}\n"
"QMenuBar::item:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QMenuBar::item:enabled:selected {\n"
"        background: rgba(255, 255, 255, 40);\n"
"}\n"
"\n"
"/**********菜单**********/\n"
"QMenu {\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"QMenu::item {\n"
"        height: 22px;\n"
"        padding: 0px 25px 0px 20px;\n"
"}\n"
"QMenu::item:enabled {\n"
"        color: rgb(225, 225, 225);\n"
"}\n"
"QMenu::item:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QMenu::item:enabled:selected {\n"
"        color: rgb(230, 230, 230);\n"
"        background: rgba(255, 255, 255, 40);\n"
"}\n"
"QMenu::separator {\n"
"        height: 1px;\n"
"        background: rgb(100, 100, 100);\n"
"}\n"
"QMenu::indicator {\n"
"        width: 13px;\n"
"        height: 13px;\n"
"}\n"
"QMenu::icon {\n"
"        padding-left: 2px;\n"
"        padding-right: 2px;\n"
"}\n"
"\n"
"/**********状态栏**********/\n"
"QStatusBar {\n"
"        background: rgb(57, 58, 60);\n"
"}\n"
"QStatusBar::item {\n"
"        border: none;\n"
"        border-right: 1px solid rgb(100, 100, 100);\n"
"}\n"
"\n"
"/**********分组框**********/\n"
"QGroupBox {\n"
"        font-size: 15px;\n"
"        border: 1px solid rgb(80, 80, 80);\n"
"        border-radius: 4px;\n"
"        margin-top: 10px;\n"
"}\n"
"QGroupBox::title {\n"
"        color: rgb(175, 175, 175);\n"
"        top: -12px;\n"
"        left: 10px;\n"
"}\n"
"\n"
"/**********页签项**********/\n"
"QTabWidget::pane {\n"
"        border: none;\n"
"        border-top: 3px solid rgb(0, 160, 230);\n"
"        background: rgb(57, 58, 60);\n"
"}\n"
"QTabWidget::tab-bar {\n"
"        border: none;\n"
"}\n"
"QTabBar::tab {\n"
"        border: none;\n"
"        border-top-left-radius: 4px;\n"
"        border-top-right-radius: 4px;\n"
"        color: rgb(175, 175, 175);\n"
"        background: rgb(255, 255, 255, 30);\n"
"        height: 28px;\n"
"        min-width: 85px;\n"
"        margin-right: 5px;\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"}\n"
"QTabBar::tab:hover {\n"
"        background: rgb(255, 255, 255, 40);\n"
"}\n"
"QTabBar::tab:selected {\n"
"        color: white;\n"
"        background: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QTabWidget#tabWidget::pane {\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        background: rgb(57, 58, 60);\n"
"        margin-top: -1px;\n"
"}\n"
"\n"
"QTabBar#tabBar::tab {\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        border-bottom: none;\n"
"        background: transparent;\n"
"}\n"
"QTabBar#tabBar::tab:hover {\n"
"        color: white;\n"
"}\n"
"QTabBar#tabBar::tab:selected {\n"
"        color: white;\n"
"        background: rgb(57, 58, 60);\n"
"}\n"
"\n"
"/**********表头**********/\n"
"QHeaderView{\n"
"        border: none;\n"
"        border-bottom: 3px solid rgb(0, 160, 230);\n"
"        background: rgb(57, 58, 60);\n"
"        min-height: 30px;\n"
"}\n"
"QHeaderView::section:horizontal {\n"
"        border: none;\n"
"        color: white;\n"
"        background: transparent;\n"
"        padding-left: 5px;\n"
"}\n"
"QHeaderView::section:horizontal:hover {\n"
"        background: rgb(0, 160, 230);\n"
"}\n"
"QHeaderView::section:horizontal:pressed {\n"
"        background: rgb(0, 180, 255);\n"
"}\n"
"QHeaderView::up-arrow {\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 5px;\n"
"        image: url(:/Black/topArrow);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::up-arrow:hover, QHeaderView::up-arrow:pressed {\n"
"        image: url(:/Black/topArrowHover);\n"
"}\n"
"QHeaderView::down-arrow {\n"
"        width: 13px;\n"
"        height: 11px;\n"
"        padding-right: 5px;\n"
"        image: url(:/Black/bottomArrow);\n"
"        subcontrol-position: center right;\n"
"}\n"
"QHeaderView::down-arrow:hover, QHeaderView::down-arrow:pressed {\n"
"        image: url(:/Black/bottomArrowHover);\n"
"}\n"
"\n"
"/**********表格**********/\n"
"QTableView {\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        background: rgb(57, 58, 60);\n"
"        gridline-color: rgb(60, 60, 60);\n"
"}\n"
"QTableView::item {\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        border: none;\n"
"        background: rgb(72, 72, 74);\n"
"        border-right: 1px solid rgb(45, 45, 45);\n"
"        border-bottom: 1px solid rgb(45, 45, 45);\n"
"}\n"
"QTableView::item:selected {\n"
"        background: rgba(255, 255, 255, 40);\n"
"}\n"
"QTableView::item:selected:!active {\n"
"        color: white;\n"
"}\n"
"QTableView::indicator {\n"
"        width: 20px;\n"
"        height: 20px;\n"
"}\n"
"QTableView::indicator:enabled:unchecked {\n"
"        image: url(:/Black/checkBox);\n"
"}\n"
"QTableView::indicator:enabled:unchecked:hover {\n"
"        image: url(:/Black/checkBoxHover);\n"
"}\n"
"QTableView::indicator:enabled:unchecked:pressed {\n"
"        image: url(:/Black/checkBoxPressed);\n"
"}\n"
"QTableView::indicator:enabled:checked {\n"
"        image: url(:/Black/checkBoxChecked);\n"
"}\n"
"QTableView::indicator:enabled:checked:hover {\n"
"        image: url(:/Black/checkBoxCheckedHover);\n"
"}\n"
"QTableView::indicator:enabled:checked:pressed {\n"
"        image: url(:/Black/checkBoxCheckedPressed);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate {\n"
"        image: url(:/Black/checkBoxIndeterminate);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate:hover {\n"
"        image: url(:/Black/checkBoxIndeterminateHover);\n"
"}\n"
"QTableView::indicator:enabled:indeterminate:pressed {\n"
"        image: url(:/Black/checkBoxIndeterminatePressed);\n"
"}\n"
"\n"
"/**********滚动条-水平**********/\n"
"QScrollBar:horizontal {\n"
"        height: 20px;\n"
"        background: transparent;\n"
"        margin-top: 3px;\n"
"        margin-bottom: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"        height: 20px;\n"
"        min-width: 30px;\n"
"        background: rgb(68, 69, 73);\n"
"        margin-left: 15px;\n"
"        margin-right: 15px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"        background: rgb(80, 80, 80);\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"        width: 15px;\n"
"        background: transparent;\n"
"        image: url(:/Black/arrowLeft);\n"
"        subcontrol-position: left;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"        width: 15px;\n"
"        background: transparent;\n"
"        image: url(:/Black/arrowRight);\n"
"        subcontrol-position: right;\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover {\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"QScrollBar::add-line:horizontal:hover {\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/**********滚动条-垂直**********/\n"
"QScrollBar:vertical {\n"
"        width: 20px;\n"
"        background: transparent;\n"
"        margin-left: 3px;\n"
"        margin-right: 3px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"        width: 20px;\n"
"        min-height: 30px;\n"
"        background: rgb(68, 69, 73);\n"
"        margin-top: 15px;\n"
"        margin-bottom: 15px;\n"
"}\n"
"QScrollBar::handle:vertical:hover {\n"
"        background: rgb(80, 80, 80);\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"        height: 15px;\n"
"        background: transparent;\n"
"        image: url(:/Black/arrowTop);\n"
"        subcontrol-position: top;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"        height: 15px;\n"
"        background: transparent;\n"
"        image: url(:/Black/arrowBottom);\n"
"        subcontrol-position: bottom;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover {\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"QScrollBar::add-line:vertical:hover {\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"        background: transparent;\n"
"}\n"
"\n"
"QScrollBar#verticalScrollBar:vertical {\n"
"        margin-top: 30px;\n"
"}\n"
"\n"
"/**********下拉列表**********/\n"
"QComboBox {\n"
"        height: 25px;\n"
"        border-radius: 4px;\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(72, 72, 73);\n"
"}\n"
"QComboBox:enabled {\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QComboBox:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QComboBox:enabled:hover, QComboBox:enabled:focus {\n"
"        color: rgb(230, 230, 230);\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"QComboBox::drop-down {\n"
"        width: 20px;\n"
"        border: none;\n"
"        background: transparent;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"        background: rgba(255, 255, 255, 30);\n"
"}\n"
"QComboBox::down-arrow {\n"
"        image: url(:/Black/arrowBottom);\n"
"}\n"
"QComboBox::down-arrow:on {\n"
"        /**top: 1px;**/\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(68, 69, 73);\n"
"        outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item {\n"
"        height: 25px;\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"        background: rgba(255, 255, 255, 40);\n"
"        color: rgb(230, 230, 230);\n"
"}\n"
"\n"
"/**********进度条**********/\n"
"QProgressBar{\n"
"        border: none;\n"
"        text-align: center;\n"
"        color: white;\n"
"        background: rgb(48, 50, 51);\n"
"}\n"
"QProgressBar::chunk {\n"
"        background: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QProgressBar#progressBar {\n"
"        border: none;\n"
"        text-align: center;\n"
"        color: white;\n"
"        background-color: transparent;\n"
"        background-image: url(\":/Black/progressBar\");\n"
"        background-repeat: repeat-x;\n"
"}\n"
"QProgressBar#progressBar::chunk {\n"
"        border: none;\n"
"        background-color: transparent;\n"
"        background-image: url(\":/Black/progressBarChunk\");\n"
"        background-repeat: repeat-x;\n"
"}\n"
"\n"
"/**********复选框**********/\n"
"QCheckBox{\n"
"        spacing: 5px;\n"
"}\n"
"QCheckBox:enabled{\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QCheckBox:enabled:hover{\n"
"        color: rgb(200, 200, 200);\n"
"}\n"
"QCheckBox:!enabled{\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QCheckBox::indicator {\n"
"        width: 20px;\n"
"        height: 20px;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"        image: url(:/Black/checkBox);\n"
"}\n"
"QCheckBox::indicator:unchecked:hover {\n"
"        image: url(:/Black/checkBoxHover);\n"
"}\n"
"QCheckBox::indicator:unchecked:pressed {\n"
"        image: url(:/Black/checkBoxPressed);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"        image: url(:/Black/checkBoxChecked);\n"
"}\n"
"QCheckBox::indicator:checked:hover {\n"
"        image: url(:/Black/checkBoxCheckedHover);\n"
"}\n"
"QCheckBox::indicator:checked:pressed {\n"
"        image: url(:/Black/checkBoxCheckedPressed);\n"
"}\n"
"QCheckBox::indicator:indeterminate {\n"
"        image: url(:/Black/checkBoxIndeterminate);\n"
"}\n"
"QCheckBox::indicator:indeterminate:hover {\n"
"        image: url(:/Black/checkBoxIndeterminateHover);\n"
"}\n"
"QCheckBox::indicator:indeterminate:pressed {\n"
"        image: url(:/Black/checkBoxIndeterminatePressed);\n"
"}\n"
"\n"
"/**********单选框**********/\n"
"QRadioButton{\n"
"        spacing: 5px;\n"
"}\n"
"QRadioButton:enabled{\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QRadioButton:enabled:hover{\n"
"        color: rgb(200, 200, 200);\n"
"}\n"
"QRadioButton:!enabled{\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"QRadioButton::indicator {\n"
"        width: 20px;\n"
"        height: 20px;\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"        image: url(:/Black/radioButton);\n"
"}\n"
"QRadioButton::indicator:unchecked:hover {\n"
"        image: url(:/Black/radioButtonHover);\n"
"}\n"
"QRadioButton::indicator:unchecked:pressed {\n"
"        image: url(:/Black/radioButtonPressed);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"        image: url(:/Black/radioButtonChecked);\n"
"}\n"
"QRadioButton::indicator:checked:hover {\n"
"        image: url(:/Black/radioButtonCheckedHover);\n"
"}\n"
"QRadioButton::indicator:checked:pressed {\n"
"        image: url(:/Black/radioButtonCheckedPressed);\n"
"}\n"
"\n"
"/**********输入框**********/\n"
"QLineEdit {\n"
"        border-radius: 4px;\n"
"        height: 25px;\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(72, 72, 73);\n"
"}\n"
"QLineEdit:enabled {\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QLineEdit:enabled:hover, QLineEdit:enabled:focus {\n"
"        color: rgb(230, 230, 230);\n"
"}\n"
"QLineEdit:!enabled {\n"
"        color: rgb(155, 155, 155);\n"
"}\n"
"\n"
"/**********文本编辑框**********/\n"
"QTextEdit {\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        color: rgb(175, 175, 175);\n"
"        background: rgb(57, 58, 60);\n"
"}\n"
"\n"
"/**********滚动区域**********/\n"
"QScrollArea {\n"
"        border: 1px solid rgb(45, 45, 45);\n"
"        background: rgb(57, 58, 60);\n"
"}\n"
"\n"
"/**********滚动区域**********/\n"
"QWidget#transparentWidget {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/**********微调器**********/\n"
"QSpinBox {\n"
"        border-radius: 4px;\n"
"        height: 24px;\n"
"        min-width: 40px;\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(68, 69, 73);\n"
"}\n"
"QSpinBox:enabled {\n"
"        color: rgb(220, 220, 220);\n"
"}\n"
"QSpinBox:enabled:hover, QLineEdit:enabled:focus {\n"
"        color: rgb(230, 230, 230);\n"
"}\n"
"QSpinBox:!enabled {\n"
"        color: rgb(65, 65, 65);\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::up-button {\n"
"        width: 18px;\n"
"        height: 12px;\n"
"        border-top-right-radius: 4px;\n"
"        border-left: 1px solid rgb(100, 100, 100);\n"
"        image: url(:/Black/upButton);\n"
"        background: rgb(50, 50, 50);\n"
"}\n"
"QSpinBox::up-button:!enabled {\n"
"        border-left: 1px solid gray;\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::up-button:enabled:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"QSpinBox::down-button {\n"
"        width: 18px;\n"
"        height: 12px;\n"
"        border-bottom-right-radius: 4px;\n"
"        border-left: 1px solid rgb(100, 100, 100);\n"
"        image: url(:/Black/downButton);\n"
"        background: rgb(50, 50, 50);\n"
"}\n"
"QSpinBox::down-button:!enabled {\n"
"        border-left: 1px solid gray;\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::down-button:enabled:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"\n"
"/**********标签**********/\n"
"QLabel#grayLabel {\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"\n"
"QLabel#highlightLabel {\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"\n"
"QLabel#redLabel {\n"
"        color: red;\n"
"}\n"
"\n"
"QLabel#grayYaHeiLabel {\n"
"        color: rgb(175, 175, 175);\n"
"        font-size: 16px;\n"
"}\n"
"\n"
"QLabel#blueLabel {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#listLabel {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#lineBlueLabel {\n"
"        background: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#graySeperateLabel {\n"
"        background: rgb(45, 45, 45);\n"
"}\n"
"\n"
"QLabel#seperateLabel {\n"
"        background: rgb(80, 80, 80);\n"
"}\n"
"\n"
"QLabel#radiusBlueLabel {\n"
"        border-radius: 15px;\n"
"        color: white;\n"
"        font-size: 16px;\n"
"        background: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#skinLabel[colorProperty=\"normal\"] {\n"
"        color: rgb(175, 175, 175);\n"
"}\n"
"QLabel#skinLabel[colorProperty=\"highlight\"] {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QLabel#informationLabel {\n"
"        qproperty-pixmap: url(:/Black/information);\n"
"}\n"
"\n"
"QLabel#errorLabel {\n"
"        qproperty-pixmap: url(:/Black/error);\n"
"}\n"
"\n"
"QLabel#successLabel {\n"
"        qproperty-pixmap: url(:/Black/success);\n"
"}\n"
"\n"
"QLabel#questionLabel {\n"
"        qproperty-pixmap: url(:/Black/question);\n"
"}\n"
"\n"
"QLabel#warningLabel {\n"
"        qproperty-pixmap: url(:/Black/warning);\n"
"}\n"
"\n"
"QLabel#groupLabel {\n"
"        color: rgb(0, 160, 230);\n"
"        border: 1px solid rgb(0, 160, 230);\n"
"        font-size: 15px;\n"
"        border-top-color: transparent;\n"
"        border-right-color: transparent;\n"
"        border-left-color: transparent;\n"
"}\n"
"\n"
"/**********按钮**********/\n"
"QToolButton#nsccButton{\n"
"        border: none;\n"
"        color: rgb(175, 175, 175);\n"
"        background: transparent;\n"
"        padding: 10px;\n"
"        qproperty-icon: url(:/Black/nscc);\n"
"        qproperty-iconSize: 32px 32px;\n"
"        qproperty-toolButtonStyle: ToolButtonTextUnderIcon;\n"
"}\n"
"QToolButton#nsccButton:hover{\n"
"        color: rgb(217, 218, 218);\n"
"        background: rgb(255, 255, 255, 20);\n"
"}\n"
"\n"
"QToolButton#transferButton{\n"
"        border: none;\n"
"        color: rgb(175, 175, 175);\n"
"        background: transparent;\n"
"        padding: 10px;\n"
"        qproperty-icon: url(:/Black/transfer);\n"
"        qproperty-iconSize: 32px 32px;\n"
"        qproperty-toolButtonStyle: ToolButtonTextUnderIcon;\n"
"}\n"
"QToolButton#transferButton:hover{\n"
"        color: rgb(217, 218, 218);\n"
"        background: rgb(255, 255, 255, 20);\n"
"}\n"
"\n"
"/**********按钮**********/\n"
"QPushButton{\n"
"        border-radius: 4px;\n"
"        border: none;\n"
"        width: 75px;\n"
"        height: 25px;\n"
"}\n"
"QPushButton:enabled {\n"
"        background: rgb(68, 69, 73);\n"
"        color: white;\n"
"}\n"
"QPushButton:!enabled {\n"
"        background: rgb(100, 100, 100);\n"
"        color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:enabled:hover{\n"
"        background: rgb(85, 85, 85);\n"
"}\n"
"QPushButton:enabled:pressed{\n"
"        background: rgb(80, 80, 80);\n"
"}\n"
"\n"
"QPushButton#blueButton {\n"
"        color: white;\n"
"}\n"
"QPushButton#blueButton:enabled {\n"
"        background: rgb(0, 165, 235);\n"
"        color: white;\n"
"}\n"
"QPushButton#blueButton:!enabled {\n"
"        background: gray;\n"
"        color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton#blueButton:enabled:hover {\n"
"        background: rgb(0, 180, 255);\n"
"}\n"
"QPushButton#blueButton:enabled:pressed {\n"
"        background: rgb(0, 140, 215);\n"
"}\n"
"\n"
"QPushButton#selectButton {\n"
"        border: none;\n"
"        border-radius: none;\n"
"        border-left: 1px solid rgb(100, 100, 100);\n"
"        image: url(:/Black/scan);\n"
"        background: transparent;\n"
"        color: white;\n"
"}\n"
"QPushButton#selectButton:enabled:hover{\n"
"        background: rgb(85, 85, 85);\n"
"}\n"
"QPushButton#selectButton:enabled:pressed{\n"
"        background: rgb(80, 80, 80);\n"
"}\n"
"\n"
"QPushButton#linkButton {\n"
"        background: transparent;\n"
"        color: rgb(0, 160, 230);\n"
"        text-align:left;\n"
"}\n"
"QPushButton#linkButton:hover {\n"
"        color: rgb(20, 185, 255);\n"
"        text-decoration: underline;\n"
"}\n"
"QPushButton#linkButton:pressed {\n"
"        color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QPushButton#transparentButton {\n"
"        background: transparent;\n"
"}\n"
"\n"
"/*****************标题栏按钮*******************/\n"
"QPushButton#minimizeButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(50, 50, 50);\n"
"        image: url(:/Black/minimize);\n"
"}\n"
"QPushButton#minimizeButton:hover {\n"
"        background: rgb(60, 60, 60);\n"
"        image: url(:/Black/minimizeHover);\n"
"}\n"
"QPushButton#minimizeButton:pressed {\n"
"        background: rgb(55, 55, 55);\n"
"        image: url(:/Black/minimizePressed);\n"
"}\n"
"\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"] {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(50, 50, 50);\n"
"        image: url(:/Black/maximize);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"]:hover {\n"
"        background: rgb(60, 60, 60);\n"
"        image: url(:/Black/maximizeHover);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"maximize\"]:pressed {\n"
"        background: rgb(55, 55, 55);\n"
"        image: url(:/Black/maximizePressed);\n"
"}\n"
"\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"] {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(50, 50, 50);\n"
"        image: url(:/Black/restore);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"]:hover {\n"
"        background: rgb(60, 60, 60);\n"
"        image: url(:/Black/restoreHover);\n"
"}\n"
"QPushButton#maximizeButton[maximizeProperty=\"restore\"]:pressed {\n"
"        background: rgb(55, 55, 55);\n"
"        image: url(:/Black/restorePressed);\n"
"}\n"
"\n"
"QPushButton#closeButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(50, 50, 50);\n"
"        image: url(:/Black/close);\n"
"}\n"
"QPushButton#closeButton:hover {\n"
"        background: rgb(60, 60, 60);\n"
"        image: url(:/Black/closeHover);\n"
"}\n"
"QPushButton#closeButton:pressed {\n"
"        background: rgb(55, 55, 55);\n"
"        image: url(:/Black/closePressed);\n"
"}\n"
"\n"
"QPushButton#skinButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(50, 50, 50);\n"
"        image: url(:/Black/skin);\n"
"}\n"
"QPushButton#skinButton:hover {\n"
"        background: rgb(60, 60, 60);\n"
"        image: url(:/Black/skinHover);\n"
"}\n"
"QPushButton#skinButton:pressed {\n"
"        background: rgb(55, 55, 55);\n"
"        image: url(:/Black/skinPressed);\n"
"}\n"
"\n"
"QPushButton#feedbackButton {\n"
"        border-radius: none;\n"
"        border-bottom-left-radius: 4px;\n"
"        border-bottom-right-radius: 4px;\n"
"        background: rgb(50, 50, 50);\n"
"        image: url(:/Black/feedback);\n"
"}\n"
"QPushButton#feedbackButton:hover {\n"
"        background: rgb(60, 60, 60);\n"
"        image: url(:/Black/feedbackHover);\n"
"}\n"
"QPushButton#feedbackButton:pressed {\n"
"        background: rgb(55, 55, 55);\n"
"        image: url(:/Black/feedbackPressed);\n"
"}\n"
"\n"
"QPushButton#closeTipButton {\n"
"        border-radius: none;\n"
"        border-image: url(:/Black/close);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#closeTipButton:hover {\n"
"        border-image: url(:/Black/closeHover);\n"
"}\n"
"QPushButton#closeTipButton:pressed {\n"
"        border-image: url(:/Black/closePressed);\n"
"}\n"
"\n"
"QPushButton#changeSkinButton{\n"
"        border-radius: 4px;\n"
"        border: 2px solid rgb(41, 41, 41);\n"
"        background: rgb(51, 51, 51);\n"
"}\n"
"QPushButton#changeSkinButton:hover{\n"
"        border-color: rgb(45, 45, 45);\n"
"}\n"
"QPushButton#changeSkinButton:pressed, QPushButton#changeSkinButton:checked{\n"
"        border-color: rgb(0, 160, 230);\n"
"}\n"
"\n"
"QPushButton#transferButton {\n"
"        padding-left: 5px;\n"
"        padding-right: 5px;\n"
"        color: white;\n"
"        background: rgb(0, 165, 235);\n"
"}\n"
"QPushButton#transferButton:hover {\n"
"        background: rgb(0, 180, 255);\n"
"}\n"
"QPushButton#transferButton:pressed {\n"
"        background: rgb(0, 140, 215);\n"
"}\n"
"QPushButton#transferButton[iconProperty=\"left\"] {\n"
"        qproperty-icon: url(:/Black/left);\n"
"}\n"
"QPushButton#transferButton[iconProperty=\"right\"] {\n"
"        qproperty-icon: url(:/Black/right);\n"
"}\n"
"\n"
"QPushButton#openButton {\n"
"        border-radius: none;\n"
"        image: url(:/Black/open);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#openButton:hover {\n"
"        image: url(:/Black/openHover);\n"
"}\n"
"QPushButton#openButton:pressed {\n"
"        image: url(:/Black/openPressed);\n"
"}\n"
"\n"
"QPushButton#deleteButton {\n"
"        border-radius: none;\n"
"        image: url(:/Black/delete);\n"
"        background: transparent;\n"
"}\n"
"QPushButton#deleteButton:hover {\n"
"        image: url(:/Black/deleteHover);\n"
"}\n"
"QPushButton#deleteButton:pressed {\n"
"        image: url(:/Black/deletePressed);\n"
"}\n"
"\n"
"QPushButton#menuButton {\n"
"        text-align: left center;\n"
"        padding-left: 3px;\n"
"        color: rgb(175, 175, 175);\n"
"        border: 1px solid rgb(100, 100, 100);\n"
"        background: rgb(72, 72, 73);\n"
"}\n"
"QPushButton#menuButton::menu-indicator{\n"
"        subcontrol-position: right center;\n"
"        subcontrol-origin: padding;\n"
"        image: url(:/Black/arrowBottom);\n"
"        padding-right: 3px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.serverAddrLabel = QtWidgets.QLabel(self.centralwidget)
        self.serverAddrLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.serverAddrLabel.setObjectName("serverAddrLabel")
        self.horizontalLayout_2.addWidget(self.serverAddrLabel)
        self.serverAddrEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.serverAddrEdit.setObjectName("serverAddrEdit")
        self.horizontalLayout_2.addWidget(self.serverAddrEdit)
        self.serverPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.serverPortLabel.setObjectName("serverPortLabel")
        self.horizontalLayout_2.addWidget(self.serverPortLabel)
        self.serverPortEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.serverPortEdit.setObjectName("serverPortEdit")
        self.horizontalLayout_2.addWidget(self.serverPortEdit)
        self.videoPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoPortLabel.setObjectName("videoPortLabel")
        self.horizontalLayout_2.addWidget(self.videoPortLabel)
        self.videoPortEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.videoPortEdit.setObjectName("videoPortEdit")
        self.horizontalLayout_2.addWidget(self.videoPortEdit)
        self.audioPortLabel = QtWidgets.QLabel(self.centralwidget)
        self.audioPortLabel.setObjectName("audioPortLabel")
        self.horizontalLayout_2.addWidget(self.audioPortLabel)
        self.audioPortEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.audioPortEdit.setObjectName("audioPortEdit")
        self.horizontalLayout_2.addWidget(self.audioPortEdit)
        self.connectButton = QtWidgets.QPushButton(self.centralwidget)
        self.connectButton.setObjectName("connectButton")
        self.horizontalLayout_2.addWidget(self.connectButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.Panel)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout.addWidget(self.horizontalSlider, 0, 0, 1, 8)
        self.playButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playButton.sizePolicy().hasHeightForWidth())
        self.playButton.setSizePolicy(sizePolicy)
        self.playButton.setObjectName("playButton")
        self.gridLayout.addWidget(self.playButton, 2, 2, 1, 1)
        self.teardownButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.teardownButton.sizePolicy().hasHeightForWidth())
        self.teardownButton.setSizePolicy(sizePolicy)
        self.teardownButton.setObjectName("teardownButton")
        self.gridLayout.addWidget(self.teardownButton, 2, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.speedButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedButton.sizePolicy().hasHeightForWidth())
        self.speedButton.setSizePolicy(sizePolicy)
        self.speedButton.setObjectName("speedButton")
        self.gridLayout.addWidget(self.speedButton, 2, 6, 1, 2)
        self.pauseButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pauseButton.sizePolicy().hasHeightForWidth())
        self.pauseButton.setSizePolicy(sizePolicy)
        self.pauseButton.setObjectName("pauseButton")
        self.gridLayout.addWidget(self.pauseButton, 2, 3, 1, 1)
        self.setupButton = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setupButton.sizePolicy().hasHeightForWidth())
        self.setupButton.setSizePolicy(sizePolicy)
        self.setupButton.setObjectName("setupButton")
        self.gridLayout.addWidget(self.setupButton, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 5, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 6, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(625, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.refreshButton = QtWidgets.QPushButton(self.centralwidget)
        self.refreshButton.setObjectName("refreshButton")
        self.horizontalLayout_3.addWidget(self.refreshButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "一盘隆的视频播放器"))
        self.serverAddrLabel.setText(_translate("MainWindow", "serverAddr"))
        self.serverAddrEdit.setText(_translate("MainWindow", "127.0.0.1"))
        self.serverPortLabel.setText(_translate("MainWindow", "serverPort"))
        self.serverPortEdit.setText(_translate("MainWindow", "9707"))
        self.videoPortLabel.setText(_translate("MainWindow", "videoPort"))
        self.videoPortEdit.setText(_translate("MainWindow", "9808"))
        self.audioPortLabel.setText(_translate("MainWindow", "audioPort"))
        self.audioPortEdit.setText(_translate("MainWindow", "9809"))
        self.connectButton.setText(_translate("MainWindow", "Connect!"))
        self.playButton.setText(_translate("MainWindow", "Play"))
        self.teardownButton.setText(_translate("MainWindow", "Teardown"))
        self.label_2.setText(_translate("MainWindow", "0:00"))
        self.speedButton.setText(_translate("MainWindow", "Speed:X1"))
        self.pauseButton.setText(_translate("MainWindow", "Pause"))
        self.setupButton.setText(_translate("MainWindow", "Setup"))
        self.label_3.setText(_translate("MainWindow", "--:--"))
        self.refreshButton.setText(_translate("MainWindow", "Refresh"))

